export const strings = {
    en: {
      appTitle1: 'Edit',
      appTitle2: 'and save to reload',
    },
    de: {
      appTitle1: 'Editiere',
      appTitle2: 'und speichere ab um neu zu laden',
    },
    es: {
        appTitle1: 'Editar',
        appTitle2: 'y guardar para re deployar',
        'Sign In': 'Accede aquí',
        'Sign in to your account':'Entra con tu cuenta',
        'Username *':'Usuario *',
        'Enter your username':'Escribe tu usuario',
        'Password *':'Contraseña *',
        'Enter your password':'Escribe tu contraseña',
        'Forgot your password?':'¿Olvidaste tu contraseña?',
        'Reset password':'Restablece tu contraseña',
        'No account?':'¿No tienes cuenta?',
        'Create account':'Crea tu cuenta',
        'Reset your password':'Reestablece tu contraseña',
        'Back to Sign In':'Regresar a inicio',
        'Send Code':'Enviar código',
        'Username':'Usuario',
        'Password':'Contraseña',
        'Email':'Correo Electrónico',
        'Email Address *':'Correo Electrónico *',
        'Phone Number *':'Teléfono *',
        'Have an account?':'¿Ya tienes cuenta?',
        'Sign in':'Iniciar sesión',
        'Create Account':'Crear cuenta',
        'Create a new account':'Crear cuenta nueva',
        'User does not exist.': 'Usario no existente',
        'User already exists':'Usuario ya existente',
        'Incorrect username or password.':'Usuario o contraseña incorrectos',
        'Invalid password format.':'Formato de contraseña incorrecto',
        'Invalid phone number format.':'Formato incorrecto de telefono',
        'Invalid email address format.': 'Formato de dirección de correo electrónico incorrecto',
        '1 validation error detected: Value at \'password\' failed to satisfy constraint: Member must have length greater than or equal to 6': 'Error de validación: La contraseña tiene que ser de longitud igual o mayor a 9',
        'Confirm Sign up':'Confirmación de cuenta',
        'Confirmation Code':'Código de confirmación',
        'Enter your code':'Código que te llegó por correo electrónico',
        'Lost your code?':'¿Perdiste tu código?',
        'Resend Code':'Reenviar código',
        'Confirm':'Confirmar',
        'Sign Out': 'Terminar sesión',
      },
  };